# Matrices con Python

Todo el trabajo con matrices se realiza con la librería Numpy

In [2]:
row=[1,2,3] #Realmente así sólo es un formato lista
row

[1, 2, 3]

In [4]:
col=[[1],[2],[3]] #Cuando creamos una matriz columna aparece cada entrada(elemento) entre corchetes
col

[[1], [2], [3]]

Para acceder a elementos utilizaríamos M[1][1] sería el elemento M22 (Recuerda que en Python la primera posición corresponde siempre al 0
El elemento M11 sería M[0][0]


In [5]:
M=[[2,-1,0],[2,5,-3],[-1,1,0]]
M

[[2, -1, 0], [2, 5, -3], [-1, 1, 0]]

In [6]:
M[0][0]

2

In [7]:
M[1][2]   #nos da el elemento M23

-3

Cuando trabajamos con matrices en Numpy el formato ya no es una lista, sino un array

El parámetro es dtype que nos permite indicar el tipo de dato que son los elementos: int, float, complex...

Si no indicamos nada, por defecto los considera enteros: int

In [10]:
import numpy as np
M=np.array([[2,-1,0],[2,5,-3],[-1,1,0]], dtype=complex)
print(M)

[[ 2.+0.j -1.+0.j  0.+0.j]
 [ 2.+0.j  5.+0.j -3.+0.j]
 [-1.+0.j  1.+0.j  0.+0.j]]


In [11]:
M=np.array([[2,-1,0],[2,5,-3],[-1,1,0]], dtype=float)
print(M)

[[ 2. -1.  0.]
 [ 2.  5. -3.]
 [-1.  1.  0.]]


In [12]:
M=np.array([[2,-1,0],[2,5,-3],[-1,1,0]])
print(M)

[[ 2 -1  0]
 [ 2  5 -3]
 [-1  1  0]]


In [13]:
#Para acceder al elemento M13
M[0,2]

0

In [14]:
#Para acceder a una fila: a la fila 3
M[2,]

array([-1,  1,  0])

In [15]:
M[2,:]

array([-1,  1,  0])

In [17]:
#y para acceder a la columna 1
M[:,0]

array([ 2,  2, -1])

Creación de matrices

Cómo crear una matriz de ceros: np.zeros((row,col)). (row,col) es una tupla formada por el nº de filas y el nº de columnas

Para crear una matriz de unos no.ones((row,col))



In [18]:
print(np.zeros((5,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
print(np.ones((5,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [21]:
#Para crear una matriz diagonal hay que darle primero una lista indicándoles cuáles son los valores diagonales Mii
x=[1,2,-1,3]
D=np.diag(x)
print(D)

[[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0 -1  0]
 [ 0  0  0  3]]


In [22]:
#La dimensión de la matriz se obtiene con np.shape
np.shape(D)

(4, 4)

# Manipulación de matrices

Suma de todos los elementos de una matriz: la función np.sum()

In [23]:
M=np.array([[2,-1,0],[2,5,-3],[-1,1,0]])
np.sum(M)

5

Para hacer la suma por filas o por columnas utilizamos la misma función añadiendo el parámetro axis=1  o axis=0 

In [24]:
np.sum(M, axis=0)   #nos da la suma por columnas

array([ 3,  5, -3])

In [26]:
np.sum(M,axis=1)   #nos da la suma por filas

array([1, 4, 0])

In [27]:
#y el producto de todos los elementos de una matriz
np.prod(M)

0

Podemos calcular también la media aritmética de todos los valores de la matriz, o la media calculada por filas y también la media por columnas

In [28]:
np.mean(M)

0.5555555555555556

In [29]:
np.mean(M, axis=0)

array([ 1.        ,  1.66666667, -1.        ])

In [30]:
np.mean(M, axis=1)

array([0.33333333, 1.33333333, 0.        ])

# Operaciones con matrices

Traspuesta de una matriz. La función .trasnspose(). El punto delante significa que la función no toma la matriz como argumento

El cálculo de la traza de una matriz se hace con la función .trace()

In [33]:
print(M.transpose())

[[ 2  2 -1]
 [-1  5  1]
 [ 0 -3  0]]


In [34]:
print(M.trace())

7


A la hora de realizar operaciones con matrices, todas ellas deben haber sido creadas con la misma librería.

No se pueden operar matrices creadas como listas con otras creadas con numpy

In [46]:
A=np.array([[1,2,-1],[0,1,5]])
B=np.array([[2,3,-2],[3,-1,2]])
print(A+B)

[[ 3  5 -3]
 [ 3  0  7]]


In [38]:
print(3*A-2*B)

[[-1  0  1]
 [-6  5 11]]


Para hacer el producto de matrices utilizaremos A.dot(B) que no es igual a B.dot(A)

In [43]:
A=np.array([[1,2,-1],[0,1,5]])
C=np.array([[2,1],[1,-1],[0,4]])
print(A.dot(C))

[[ 4 -5]
 [ 1 19]]


In [45]:
#Como en R si realizas la operación A*C se obtiene el resultado de multiplicar elemento a elemento
print(A*B)

[[ 2  6  2]
 [ 0 -1 10]]


Potencia de una matriz. Se utiliza la sublibrería linalg y la función matrix_power

In [48]:
P=np.array([[2,-1,3],[4,-1,0],[5,2,-2]])
print(P)

[[ 2 -1  3]
 [ 4 -1  0]
 [ 5  2 -2]]


In [49]:
print(np.linalg.matrix_power(P,3))   #Calculando P^3

[[ 50 -20  45]
 [ 56  23 -12]
 [ 67  41 -14]]


# Rango de una matriz

El rango de una matriz es el número de filas no completamente nulas una vez triangularizada la matriz.

El rango es el número de filas (y de columnas) que son linealmente independientes

In [50]:
print(np.linalg.matrix_rank(P))  #Es una matriz 3x3 con rango 3 por tanto rango completo: es una matriz regular

3


# Inversa de una matriz

In [51]:
print(np.linalg.inv(P))

[[ 0.05714286  0.11428571  0.08571429]
 [ 0.22857143 -0.54285714  0.34285714]
 [ 0.37142857 -0.25714286  0.05714286]]


In [68]:
#Comprobamos que efectivamente es la matriz inversa de P
Id=(np.linalg.inv(P).dot(P))
print(Id)

[[ 1.00000000e+00  2.77555756e-17  0.00000000e+00]
 [ 1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [-6.93889390e-17  2.77555756e-17  1.00000000e+00]]
