# Diagonalización con Python

In [5]:
#Importamos las librerías necesarias
import numpy as np
from numpy import linalg as LA   #sublibrería de numpy

In [4]:
A=np.array([[2,-2,1],[2,-8,-2],[1,2,2]])   #Definimos una matriz A que vamos a diagonalizar
print(A)

[[ 2 -2  1]
 [ 2 -8 -2]
 [ 1  2  2]]


Utilizaremos la notación: w para los autovalores (valores propios) y v para los autovectores (vectores propios)
Y vamos a utilizar la función eig(A) que nos proporciona autovalores y autovectores.

In [12]:
w,v=LA.eig(A)
w,v

(array([-7.00000000e+00,  3.00000000e+00, -1.12300315e-16]),
 array([[ 2.35702260e-01,  7.07106781e-01, -6.66666667e-01],
        [ 9.42809042e-01, -7.97713154e-17, -3.33333333e-01],
        [-2.35702260e-01,  7.07106781e-01,  6.66666667e-01]]))

In [13]:
np.around(w,2)   # tenemos los valores propios: -7,3,0

array([-7.,  3., -0.])

In [14]:
np.around(v,2)   # y también la matriz de vectores propios escritos por columnas por tanto el primer autovector es (0.24, 0.94,-0.24)

array([[ 0.24,  0.71, -0.67],
       [ 0.94, -0.  , -0.33],
       [-0.24,  0.71,  0.67]])

Recuerda que puedes tomar cualquier vector de componentes proporcionales (como vector libre sería el mismo) para obtener una notación más cómoda


In [16]:
#Si queremos obtener el primer autovalor
l1=w[0]
l1

-7.0

In [17]:
#y el primer autovector
v1=v[:,0]
v1

array([ 0.23570226,  0.94280904, -0.23570226])

In [18]:
#y podemos comprobar que efectivamente v1 es vector propio asociado al valor propio l1=-7
print(np.dot(A,v1))

[-1.64991582 -6.59966329  1.64991582]


In [19]:
print(l1*v1)

[-1.64991582 -6.59966329  1.64991582]


In [20]:
#Obien podríamos preguntarle
np.dot(A,v1)==l1*v1

array([False, False, False])

¿Qué ocurre? que al introducir tantos decimales en el cálculo, en cuanto falle uno aunque sea del orden de 10^^-15
Existe una función isclose que permite comparar números próximos

In [22]:
np.isclose(np.dot(A,v1),l1*v1)   #Así podemos comprobar la igualdad de A*v1 y l1*v1

array([ True,  True,  True])

Sabemos que la matriz de autovectores es la matriz regular P que es semejante a la matriz A, es decir tal que P^-1*A*P=D
Vamos a comprobarlo con Python

In [31]:
#Si realizamos el producto de matrices P^-1*A*P; primero calculamos P^-1 y la llamamos vInv
vInv=np.around(np.linalg.inv(v),1)
print(vInv)

[[-0.3  1.2  0.3]
 [ 0.7 -0.   0.7]
 [-0.9  0.4  0.9]]


In [34]:
R=(vInv.dot(A)).dot(v)
print(np.around(R,0))

[[-7.  0.  0.]
 [ 0.  3.  0.]
 [ 0. -0. -0.]]


In [35]:
#O bien podríamos haberlo hecho directamente
print(np.around(np.linalg.inv(v).dot(A.dot(v))))

[[-7.  0.  0.]
 [ 0.  3.  0.]
 [-0. -0.  0.]]
